services:
 airflow:
    container_name: uber_airflow
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AIRFLOW_LOAD_EXAMPLES: "n"
      AIRFLOW_CORE_EXECUTOR: "SequentialExecutor"
      AIRFLOW_CONN_GCP_CLOUD_DEFAULT: >-
        google-cloud-platform://?key_path=/opt/airflow/include/gcp/gcp_service.json&project=data-engineering-458813
    env_file:
      - .env

    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./logs:/opt/airflow/logs
      - ./include/gcp/gcp_service.json:/opt/airflow/include/gcp/gcp_service.json

    ports:
      - "8080:8080"
    networks:
      - airflow_network 
    command: >
      bash -c "airflow standalone"
networks:
  airflow_network:
    driver: bridge
